### ISSUE TITLE
Q: Correcting destinations from configuration

### ISSUE THREAD

**Issue by torsten-liermann** [mkopylec/charon-spring-boot-starter#59]
Hi,

Thanks for this handy reverse proxy. 

Is it possible to manipulate subsequent mappings from the configuration?
I need a way to put the port later.

Thanks,
Torstem

**Comment by mkopylec** [comment]
I'm not sure what you want to do but maybe a custom mappings provider is what you need: https://github.com/mkopylec/charon-spring-boot-starter#mappings
If not please provide more details.

**Comment by torsten-liermann** [comment]
More details: I like the configuration of the mapping in the application.yml. But in my case, the port `@docindex.api.port@` is determined at runtime. So it would be convenient to subsequently correct the destination URLs.
<pre>
charon:
  mappings:
    - name: forward to local external api
      path: /docindex/api
      destinations: http://127.0.0.1:@docindex.api.port@/docindex/api
</pre>


Background why dynamically ports: My spring-boot app starts an external process (via de.flapdoodle.embed) which picks a random free port for this service.

**Comment by mkopylec** [comment]
Ok, and how you would now what is the value of `@docindex.api.port@`?

**Comment by mkopylec** [comment]
If you have a solution how you can update the yml file when your backend is restarted than you could something like:
```yaml
some.port: @docindex.api.port@

charon:
  mappings:
    - name: forward to local external api
      path: /docindex/api
      destinations: http://127.0.0.1:${some.port}/docindex/api
```
