### ISSUE TITLE
Incompatibility with Spring Boot 2.1

### ISSUE THREAD

**Issue by sdavids13** [mkopylec/charon-spring-boot-starter#75]
When upgrading to Spring Boot 2.1 charon no longer works. This is because Spring Boot 2.1 now [auto-configures a Task Executor](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#task-execution) which disables the creation of the "charonTaskExecutor" due to the [\@ConditionalBean definition](https://github.com/mkopylec/charon-spring-boot-starter/blob/0a83dfdc1304a04be1f02e8217667178e802e87f/src/main/java/com/github/mkopylec/charon/configuration/CharonConfiguration.java#L121) but.. the ReverseProxyFilter specifically calls out the [\@Qualifier("charonTaskExecutor")](https://github.com/mkopylec/charon-spring-boot-starter/blob/0a83dfdc1304a04be1f02e8217667178e802e87f/src/main/java/com/github/mkopylec/charon/configuration/CharonConfiguration.java#L71) which wasn't loaded since Spring 2.1 already created a TaskExecutor. 

As a temporary work-around you can disable the TaskExecutor auto-configuration via:
```
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration #Can be removed once the Charon dependency has Spring 2.1 fix
```
